// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all_users.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_all_5fusers_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_all_5fusers_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_all_5fusers_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_all_5fusers_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_all_5fusers_2eproto;
namespace chat {
class AllUsers;
class AllUsersDefaultTypeInternal;
extern AllUsersDefaultTypeInternal _AllUsers_default_instance_;
}  // namespace chat
PROTOBUF_NAMESPACE_OPEN
template<> ::chat::AllUsers* Arena::CreateMaybeMessage<::chat::AllUsers>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace chat {

// ===================================================================

class AllUsers PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chat.AllUsers) */ {
 public:
  inline AllUsers() : AllUsers(nullptr) {};
  virtual ~AllUsers();

  AllUsers(const AllUsers& from);
  AllUsers(AllUsers&& from) noexcept
    : AllUsers() {
    *this = ::std::move(from);
  }

  inline AllUsers& operator=(const AllUsers& from) {
    CopyFrom(from);
    return *this;
  }
  inline AllUsers& operator=(AllUsers&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AllUsers& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AllUsers* internal_default_instance() {
    return reinterpret_cast<const AllUsers*>(
               &_AllUsers_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AllUsers& a, AllUsers& b) {
    a.Swap(&b);
  }
  inline void Swap(AllUsers* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AllUsers* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AllUsers* New() const final {
    return CreateMaybeMessage<AllUsers>(nullptr);
  }

  AllUsers* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AllUsers>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AllUsers& from);
  void MergeFrom(const AllUsers& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AllUsers* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chat.AllUsers";
  }
  protected:
  explicit AllUsers(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_all_5fusers_2eproto);
    return ::descriptor_table_all_5fusers_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUsernamesFieldNumber = 1,
    kStatusFieldNumber = 2,
  };
  // repeated string usernames = 1;
  int usernames_size() const;
  private:
  int _internal_usernames_size() const;
  public:
  void clear_usernames();
  const std::string& usernames(int index) const;
  std::string* mutable_usernames(int index);
  void set_usernames(int index, const std::string& value);
  void set_usernames(int index, std::string&& value);
  void set_usernames(int index, const char* value);
  void set_usernames(int index, const char* value, size_t size);
  std::string* add_usernames();
  void add_usernames(const std::string& value);
  void add_usernames(std::string&& value);
  void add_usernames(const char* value);
  void add_usernames(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& usernames() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_usernames();
  private:
  const std::string& _internal_usernames(int index) const;
  std::string* _internal_add_usernames();
  public:

  // repeated .chat.StatusEnum status = 2;
  int status_size() const;
  private:
  int _internal_status_size() const;
  public:
  void clear_status();
  private:
  ::chat::StatusEnum _internal_status(int index) const;
  void _internal_add_status(::chat::StatusEnum value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* _internal_mutable_status();
  public:
  ::chat::StatusEnum status(int index) const;
  void set_status(int index, ::chat::StatusEnum value);
  void add_status(::chat::StatusEnum value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>& status() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* mutable_status();

  // @@protoc_insertion_point(class_scope:chat.AllUsers)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> usernames_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int> status_;
  mutable std::atomic<int> _status_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_all_5fusers_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AllUsers

// repeated string usernames = 1;
inline int AllUsers::_internal_usernames_size() const {
  return usernames_.size();
}
inline int AllUsers::usernames_size() const {
  return _internal_usernames_size();
}
inline void AllUsers::clear_usernames() {
  usernames_.Clear();
}
inline std::string* AllUsers::add_usernames() {
  // @@protoc_insertion_point(field_add_mutable:chat.AllUsers.usernames)
  return _internal_add_usernames();
}
inline const std::string& AllUsers::_internal_usernames(int index) const {
  return usernames_.Get(index);
}
inline const std::string& AllUsers::usernames(int index) const {
  // @@protoc_insertion_point(field_get:chat.AllUsers.usernames)
  return _internal_usernames(index);
}
inline std::string* AllUsers::mutable_usernames(int index) {
  // @@protoc_insertion_point(field_mutable:chat.AllUsers.usernames)
  return usernames_.Mutable(index);
}
inline void AllUsers::set_usernames(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:chat.AllUsers.usernames)
  usernames_.Mutable(index)->assign(value);
}
inline void AllUsers::set_usernames(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:chat.AllUsers.usernames)
  usernames_.Mutable(index)->assign(std::move(value));
}
inline void AllUsers::set_usernames(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  usernames_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:chat.AllUsers.usernames)
}
inline void AllUsers::set_usernames(int index, const char* value, size_t size) {
  usernames_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:chat.AllUsers.usernames)
}
inline std::string* AllUsers::_internal_add_usernames() {
  return usernames_.Add();
}
inline void AllUsers::add_usernames(const std::string& value) {
  usernames_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:chat.AllUsers.usernames)
}
inline void AllUsers::add_usernames(std::string&& value) {
  usernames_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:chat.AllUsers.usernames)
}
inline void AllUsers::add_usernames(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  usernames_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:chat.AllUsers.usernames)
}
inline void AllUsers::add_usernames(const char* value, size_t size) {
  usernames_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:chat.AllUsers.usernames)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
AllUsers::usernames() const {
  // @@protoc_insertion_point(field_list:chat.AllUsers.usernames)
  return usernames_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
AllUsers::mutable_usernames() {
  // @@protoc_insertion_point(field_mutable_list:chat.AllUsers.usernames)
  return &usernames_;
}

// repeated .chat.StatusEnum status = 2;
inline int AllUsers::_internal_status_size() const {
  return status_.size();
}
inline int AllUsers::status_size() const {
  return _internal_status_size();
}
inline void AllUsers::clear_status() {
  status_.Clear();
}
inline ::chat::StatusEnum AllUsers::_internal_status(int index) const {
  return static_cast< ::chat::StatusEnum >(status_.Get(index));
}
inline ::chat::StatusEnum AllUsers::status(int index) const {
  // @@protoc_insertion_point(field_get:chat.AllUsers.status)
  return _internal_status(index);
}
inline void AllUsers::set_status(int index, ::chat::StatusEnum value) {
  status_.Set(index, value);
  // @@protoc_insertion_point(field_set:chat.AllUsers.status)
}
inline void AllUsers::_internal_add_status(::chat::StatusEnum value) {
  status_.Add(value);
}
inline void AllUsers::add_status(::chat::StatusEnum value) {
  // @@protoc_insertion_point(field_add:chat.AllUsers.status)
  _internal_add_status(value);
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>&
AllUsers::status() const {
  // @@protoc_insertion_point(field_list:chat.AllUsers.status)
  return status_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
AllUsers::_internal_mutable_status() {
  return &status_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
AllUsers::mutable_status() {
  // @@protoc_insertion_point(field_mutable_list:chat.AllUsers.status)
  return _internal_mutable_status();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace chat

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_all_5fusers_2eproto
