// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broadcast_messages.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_broadcast_5fmessages_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_broadcast_5fmessages_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_broadcast_5fmessages_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_broadcast_5fmessages_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_broadcast_5fmessages_2eproto;
namespace chat {
class BroadcastDelivery;
class BroadcastDeliveryDefaultTypeInternal;
extern BroadcastDeliveryDefaultTypeInternal _BroadcastDelivery_default_instance_;
}  // namespace chat
PROTOBUF_NAMESPACE_OPEN
template<> ::chat::BroadcastDelivery* Arena::CreateMaybeMessage<::chat::BroadcastDelivery>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace chat {

// ===================================================================

class BroadcastDelivery PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chat.BroadcastDelivery) */ {
 public:
  inline BroadcastDelivery() : BroadcastDelivery(nullptr) {};
  virtual ~BroadcastDelivery();

  BroadcastDelivery(const BroadcastDelivery& from);
  BroadcastDelivery(BroadcastDelivery&& from) noexcept
    : BroadcastDelivery() {
    *this = ::std::move(from);
  }

  inline BroadcastDelivery& operator=(const BroadcastDelivery& from) {
    CopyFrom(from);
    return *this;
  }
  inline BroadcastDelivery& operator=(BroadcastDelivery&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const BroadcastDelivery& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BroadcastDelivery* internal_default_instance() {
    return reinterpret_cast<const BroadcastDelivery*>(
               &_BroadcastDelivery_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BroadcastDelivery& a, BroadcastDelivery& b) {
    a.Swap(&b);
  }
  inline void Swap(BroadcastDelivery* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BroadcastDelivery* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BroadcastDelivery* New() const final {
    return CreateMaybeMessage<BroadcastDelivery>(nullptr);
  }

  BroadcastDelivery* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BroadcastDelivery>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BroadcastDelivery& from);
  void MergeFrom(const BroadcastDelivery& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BroadcastDelivery* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chat.BroadcastDelivery";
  }
  protected:
  explicit BroadcastDelivery(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_broadcast_5fmessages_2eproto);
    return ::descriptor_table_broadcast_5fmessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 1,
    kUsernameOriginFieldNumber = 2,
  };
  // string message = 1;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_message(
      std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // string username_origin = 2;
  void clear_username_origin();
  const std::string& username_origin() const;
  void set_username_origin(const std::string& value);
  void set_username_origin(std::string&& value);
  void set_username_origin(const char* value);
  void set_username_origin(const char* value, size_t size);
  std::string* mutable_username_origin();
  std::string* release_username_origin();
  void set_allocated_username_origin(std::string* username_origin);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_username_origin();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_username_origin(
      std::string* username_origin);
  private:
  const std::string& _internal_username_origin() const;
  void _internal_set_username_origin(const std::string& value);
  std::string* _internal_mutable_username_origin();
  public:

  // @@protoc_insertion_point(class_scope:chat.BroadcastDelivery)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr username_origin_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_broadcast_5fmessages_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BroadcastDelivery

// string message = 1;
inline void BroadcastDelivery::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& BroadcastDelivery::message() const {
  // @@protoc_insertion_point(field_get:chat.BroadcastDelivery.message)
  return _internal_message();
}
inline void BroadcastDelivery::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:chat.BroadcastDelivery.message)
}
inline std::string* BroadcastDelivery::mutable_message() {
  // @@protoc_insertion_point(field_mutable:chat.BroadcastDelivery.message)
  return _internal_mutable_message();
}
inline const std::string& BroadcastDelivery::_internal_message() const {
  return message_.Get();
}
inline void BroadcastDelivery::_internal_set_message(const std::string& value) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void BroadcastDelivery::set_message(std::string&& value) {
  
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:chat.BroadcastDelivery.message)
}
inline void BroadcastDelivery::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:chat.BroadcastDelivery.message)
}
inline void BroadcastDelivery::set_message(const char* value,
    size_t size) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:chat.BroadcastDelivery.message)
}
inline std::string* BroadcastDelivery::_internal_mutable_message() {
  
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* BroadcastDelivery::release_message() {
  // @@protoc_insertion_point(field_release:chat.BroadcastDelivery.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BroadcastDelivery::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:chat.BroadcastDelivery.message)
}
inline std::string* BroadcastDelivery::unsafe_arena_release_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:chat.BroadcastDelivery.message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void BroadcastDelivery::unsafe_arena_set_allocated_message(
    std::string* message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (message != nullptr) {
    
  } else {
    
  }
  message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:chat.BroadcastDelivery.message)
}

// string username_origin = 2;
inline void BroadcastDelivery::clear_username_origin() {
  username_origin_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& BroadcastDelivery::username_origin() const {
  // @@protoc_insertion_point(field_get:chat.BroadcastDelivery.username_origin)
  return _internal_username_origin();
}
inline void BroadcastDelivery::set_username_origin(const std::string& value) {
  _internal_set_username_origin(value);
  // @@protoc_insertion_point(field_set:chat.BroadcastDelivery.username_origin)
}
inline std::string* BroadcastDelivery::mutable_username_origin() {
  // @@protoc_insertion_point(field_mutable:chat.BroadcastDelivery.username_origin)
  return _internal_mutable_username_origin();
}
inline const std::string& BroadcastDelivery::_internal_username_origin() const {
  return username_origin_.Get();
}
inline void BroadcastDelivery::_internal_set_username_origin(const std::string& value) {
  
  username_origin_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void BroadcastDelivery::set_username_origin(std::string&& value) {
  
  username_origin_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:chat.BroadcastDelivery.username_origin)
}
inline void BroadcastDelivery::set_username_origin(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  username_origin_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:chat.BroadcastDelivery.username_origin)
}
inline void BroadcastDelivery::set_username_origin(const char* value,
    size_t size) {
  
  username_origin_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:chat.BroadcastDelivery.username_origin)
}
inline std::string* BroadcastDelivery::_internal_mutable_username_origin() {
  
  return username_origin_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* BroadcastDelivery::release_username_origin() {
  // @@protoc_insertion_point(field_release:chat.BroadcastDelivery.username_origin)
  return username_origin_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BroadcastDelivery::set_allocated_username_origin(std::string* username_origin) {
  if (username_origin != nullptr) {
    
  } else {
    
  }
  username_origin_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), username_origin,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:chat.BroadcastDelivery.username_origin)
}
inline std::string* BroadcastDelivery::unsafe_arena_release_username_origin() {
  // @@protoc_insertion_point(field_unsafe_arena_release:chat.BroadcastDelivery.username_origin)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return username_origin_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void BroadcastDelivery::unsafe_arena_set_allocated_username_origin(
    std::string* username_origin) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (username_origin != nullptr) {
    
  } else {
    
  }
  username_origin_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      username_origin, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:chat.BroadcastDelivery.username_origin)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace chat

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_broadcast_5fmessages_2eproto
